// Build-time OG image endpoint for blog posts.
// Emits dist/blog/og/<slug>.png, one per post. Consumed by Layout.astro via
// metadata.image in src/pages/blog/[...slug].astro.
//
// Pattern from https://nerdpress.org/2025/12/23/dynamic-opengraph-images-in-astro/
// Uses astro-og-canvas (CanvasKit-WASM) — no headless browser, no pre-build step,
// integrated directly with Astro's build. Works in `output: 'static'` mode.
//
// Visual polish is baked into PRE-RENDERED assets (generated by
// scripts/gen-og-assets.mjs) because astro-og-canvas has no support for
// rounded frames, drop-shadows, or multiple text regions:
//   bg.png            — orange gradient + inset rounded navy frame
//                       + "KARENZ-WIZARD.AT" watermark (lower-right)
//   wizard-shadow.png — wizard with a baked-in soft drop-shadow
import { OGImageRoute } from 'astro-og-canvas';
import { getCollection } from 'astro:content';

const posts = await getCollection('blog');

// post.data.slug is the source-of-truth slug (frontmatter), mirroring
// src/pages/blog/[...slug].astro:12-18. The `param: 'slug'` below must match
// the `[slug]` segment in this file's path.
const pages = Object.fromEntries(
  posts.map((post) => [post.data.slug, { data: post.data }])
);

// Cap title length at ~3 lines of wrapped text at the chosen size (48 px Bold
// Inter over a ~960 px paragraph width). Empirically 85 chars ≈ 3 lines; the
// observed 84-char `mutter-startet-volksbegehren` title fits exactly. Longer
// titles get ellipsised to avoid clipping at the bottom of the card.
const MAX_TITLE_CHARS = 85;
const fitTitle = (t: string) =>
  t.length <= MAX_TITLE_CHARS ? t : t.slice(0, MAX_TITLE_CHARS - 1).trimEnd() + '…';

// LAYOUT NOTE — astro-og-canvas has only two text slots (title, description),
// drawn stacked beneath the logo which sits in the upper-left corner
// (see node_modules/astro-og-canvas/dist/generateOpenGraphImage.js:171-218).
// Design calls for:
//   [wizard]  NEU IM BLOG      <- eyebrow (small, uppercase)
//             Post title…      <- post title (large, bold)
// Since the library's `title` is drawn ABOVE `description`, we SWAP semantics:
// eyebrow goes in `title`, post title goes in `description`, sized accordingly.
//
// Vertical behaviour & "grow upward" — the library's rule is
//   paraTop = clamp(naturalTop, minTop, maxTop)
//   minTop  = padding + logoH + padding
//   maxTop  = minTop + padding
// i.e. the paragraph can only float within a narrow `padding`-wide window
// just below the logo. Short paragraphs clamp to maxTop; tall paragraphs
// clamp to minTop (and may overflow bottom). True bottom-anchoring would
// require forking the library. Current tuning (padding=80, logoH≈197):
//   1-line title → paraTop ≈ 437 (low on card)
//   2-line title → paraTop ≈ 380 (rises ~57 px)
//   3-line title → paraTop ≈ 357 (rises ~80 px, tight bottom margin)
// → partial "grow upward" as titles lengthen.
//
// Visible-edge alignment — wizard-shadow.png has asymmetric padding
// (~6 px left/top, ~60 px right/bottom; see scripts/gen-og-assets.mjs). That
// way when drawn at (padding, padding) the visible wizard sits effectively
// in the top-left corner AND its visible left edge aligns with the
// eyebrow / title left edge (both start at x=padding on the card).
//
export const { getStaticPaths, GET } = await OGImageRoute({
  param: 'slug',
  pages,
  getImageOptions: (_slug, { data }) => ({
    title: 'NEU IM BLOG',
    description: fitTitle(data.title),
    // Background PNG contains the gradient + inset rounded navy frame.
    bgImage: {
      path: './src/assets/og/bg.png',
      fit: 'cover',
    },
    // Larger padding = more breathing room around the wizard and between
    // wizard and title. Library uses this same value for all four margins
    // AND the logo↔text gap.
    padding: 80,
    // Wizard with baked-in drop-shadow. Native canvas is 366×361 (wizard
    // 300×295 + asymmetric shadow padding). Rendered at [200, 197] — big
    // enough to feel present, small enough to leave room for 2–3 title
    // lines.
    logo: {
      path: './src/assets/og/wizard-shadow.png',
      size: [200, 197],
    },
    font: {
      // Eyebrow — "NEU IM BLOG"
      title: {
        families: ['Inter'],
        weight: 'SemiBold',
        size: 22,
        color: [28, 47, 63],
        lineHeight: 1.3,
      },
      // Actual post title — the largest text on the card.
      description: {
        families: ['Inter'],
        weight: 'Bold',
        size: 48,
        color: [28, 47, 63],
        lineHeight: 1.2,
      },
    },
    fonts: [
      './src/assets/og/fonts/Inter-Bold.ttf',
      './src/assets/og/fonts/Inter-SemiBold.ttf',
    ],
    format: 'PNG',
  }),
});
